server:
  port: 8080   # Thay port
  error:
    include-message: always
    include-binding-errors: always

vehicle-service:
  url: http://localhost:8002/
user-service:
  url: http://localhost:8001/
part-service:
  url: http://localhost:8004/
warranty-service:
  url: http://localhost:8005/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

spring:
  application:
    name: OEM_EV_WARRANTY_MANAGEMENT_SYSTEM

  datasource:
    url: "jdbc:mysql://mysql-db:3306/campaign_service?createDatabaseIfNotExist=true&autoReconnect=true&connectTimeout=30000"
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: 1234
      roles: ADMIN

  main:
    allow-bean-definition-overriding: true
app:
  internal-secret: ${INTERNAL_SERVICE_SECRET}
