server:
  port: 8080   # Thay port
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: OEM_EV_WARRANTY_MANAGEMENT_SYSTEM

  datasource:
    url: "jdbc:mysql://mysql-db:3306/campaign_service?createDatabaseIfNotExist=true&autoReconnect=true&connectTimeout=30000"
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: 1234
      roles: ADMIN
