server:
  port: 8001
  servlet:
    context-path: /vehicle-service

spring:
  application:
    name: OEM_EV_WARRANTY_MANAGEMENT_SYSTEM
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect