server:
  port: 8005
# Cấu hình Feign Clients:
vehicle-service:
  url: http://localhost:8002/ # Giả sử Vehicle Service chạy ở port 8081
user-service:
  url: http://localhost:8001/ # Giả sử User Service chạy ở port 8082
part-service:
  url: http://localhost:8004/ # Giả sử Part Service chạy ở port 8083
campaign-service:
  url: http://localhost:8003/ # Giả sử Campaign Service chạy ở port 8084
# Cấu hình Feign timeout (giúp tránh chờ đợi quá lâu)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000


spring:
  application:
    name: OEM_EV_WARRANTY_MANAGEMENT_SYSTEM
  datasource:
    url: "jdbc:mysql://localhost:3306/warranty-serviceDB?createDatabaseIfNotExist=true"
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

