server:
  port: 8080

spring:
  application:
    name: user-service

  # --- [THÊM ĐOẠN NÀY ĐỂ FIX LỖI JSON DATE] ---
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Asia/Ho_Chi_Minh
    default-property-inclusion: non_null
  # --------------------------------------------

  datasource:
    url: jdbc:mysql://mysql-db:3306/user_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&connectTimeout=30000
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis-cache}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 60000

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: password123
    listener:
      simple:
        acknowledge-mode: auto
  sql:
    init:
      mode: always

  security:
    user:
      name: admin
      password: 1234
      roles: ADMIN
  main:
    allow-bean-definition-overriding: true

service:
  vehicle:
    url: http://vehicle-service:8080
  warranty:
    url: http://warranty-service:8080
  part:
    url: http://part-service:8080
  campaign:
    url: http://campaign-service:8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

circuitbreaker:
  enabled: true

logging:
  level:
    root: INFO
    org.springframework.cache: DEBUG
    com.oem.evwarranty: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: always

app:
  internal-secret: ${INTERNAL_SERVICE_SECRET}
  rabbitmq:
    exchange: oem.internal.exchange
    queue: vehicle.user.created.queue # Tên hàng đợi riêng cho Vehicle Service
    routing-key: user.created
jwt:
  secret: ${JWT_SECRET}