server:
  port: 8004 #Thay port cho moi service
app:
  security:
    enabled: false  # 🚀 false = bỏ xác thực, true = bật xác thực

logging:
  level:
    org.springframework: DEBUG

spring:
  application:
    name: OEM_EV_WARRANTY_MANAGEMENT_SYSTEM
  datasource:
    url: "jdbc:mysql://localhost:3306/part_service"
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Các service URL (tốt, giữ nguyên)
vehicle-service:
  url: http://vehicle-service:8080/
user-service:
  url: http://user-service:8080/
warranty-service:
  url: http://warranty-service:8080/
campaign-service:
  url: http://campaign-service:8080/


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full

